# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)

<<<<<<< HEAD
Person.create([{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Aleven_March09.jpg", "title"=>"Assistant Professor", "last_name"=>"Aleven", "room"=>"NSH 3613", "first_name"=>"Vincent"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/anderson.jpg", "title"=>"Richard King Mellon University Professor of Psychology and Computer Science", "last_name"=>"Anderson", "room"=>"BH 345D", "first_name"=>"John"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/atkeson2.jpg", "title"=>"Professor", "last_name"=>"Atkeson", "room"=>"NSH A527", "first_name"=>"Chris"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Cassell_184_0.jpg", "title"=>"HCII Director", "last_name"=>"Cassell", "room"=>"NSH 3519", "first_name"=>"Justine"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Corbett_March09.jpg", "title"=>"Associate Research Professor", "last_name"=>"Corbett", "room"=>"NSH 3605", "first_name"=>"Albert"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/dabbish2.jpg", "title"=>"Assistant Professor", "last_name"=>"Dabbish", "room"=>"HbH 2109C", "first_name"=>"Laura"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/20090320_DSC_0006.jpg", "title"=>"Director of MHCI", "last_name"=>"Date", "room"=>"300 S. Craig Street Suite 228", "first_name"=>"Jenna"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/davidoff-portrait-square.low-res.jpg", "title"=>"Post Doctoral Fellow", "last_name"=>"Davidoff", "room"=>"NSH 2502", "first_name"=>"Scott"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Dey_March09.jpg", "title"=>"Associate Professor", "last_name"=>"Dey", "room"=>"NSH 2502C", "first_name"=>"Anind"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/clip_image001.jpg", "title"=>"Assistant Professor", "last_name"=>"Dow", "room"=>"NSH 3615", "first_name"=>"Steven"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/03-l.jpg", "title"=>"Post Doctoral Fellow", "last_name"=>"Farzan", "room"=>"2504B NSH", "first_name"=>"Rosta"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/haakon_for_cmu_web.png", "title"=>"Visiting Assistant Professor", "last_name"=>"Faste", "room"=>"NSH 3527", "first_name"=>"Haakon"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Forlizzi_March09.jpg", "title"=>"A. Nico Habermann Associate Professor", "last_name"=>"Forlizzi", "room"=>"NSH 2504E", "first_name"=>"Jodi"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Hong_March09.jpg", "title"=>"Assistant Professor", "last_name"=>"Hong", "room"=>"NSH 3523", "first_name"=>"Jason"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Hudson_March09.jpg", "title"=>"Professor", "last_name"=>"Hudson", "room"=>"NSH 2502C", "first_name"=>"Scott"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/John_March09.jpg", "title"=>"Professor", "last_name"=>"John", "room"=>"NSH 3521", "first_name"=>"Bonnie"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Kam_March09.jpg", "title"=>"Assistant Professor", "last_name"=>"Kam", "room"=>"NSH 3525", "first_name"=>"Matthew"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/SIGCHI_Kiesler.jpg", "title"=>"Hillman Professor of Computer Science and Human-Computer Interaction", "last_name"=>"Kiesler", "room"=>"NSH 3513", "first_name"=>"Sara"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Picture+182.jpg", "title"=>"Post Doctoral Fellow", "last_name"=>"Kim", "room"=>"417 SCRG, room # 306", "first_name"=>"SeungJun"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/kittur.jpg", "title"=>"Assistant Professor", "last_name"=>"Kittur", "room"=>"NSH 2504 D", "first_name"=>"Aniket"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Klatzky_March09.jpg", "title"=>"Professor, Psychology Dept. and Center for the Neural Basis of Cognition", "last_name"=>"Klatzky", "room"=>"BH 346C", "first_name"=>"Roberta"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/ken010.jpg", "title"=>"Professor", "last_name"=>"Koedinger", "room"=>"NSH 3601", "first_name"=>"Ken"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/bob-1-2006-crop4_0.jpg", "title"=>"Herbert A. Simon Professor of Human-Computer Interaction", "last_name"=>"Kraut", "room"=>"NSH 3515", "first_name"=>"Robert"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/HCIIface2.jpg", "title"=>"Post Doctoral Fellow", "last_name"=>"Lindqvist", "room"=>"NSH 2602 West", "first_name"=>"Janne"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Mankoff_March09.jpg", "title"=>"Associate Professor", "last_name"=>"Mankoff", "room"=>"Jen&#039;s room: NSH 2405A", "first_name"=>"Jennifer"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/20090314_HCII.jpg", "title"=>"Systems Scientist", "last_name"=>"Matsuda", "room"=>"NSH 2619", "first_name"=>"Noboru"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/20090413-DSC_0196.jpg", "title"=>"Senior Systems Scientist", "last_name"=>"M.", "room"=>"NSH 2602 I", "first_name"=>"Bruce"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/morris-03-2009.jpg", "title"=>"Professor", "last_name"=>"Morris", "room"=>"GHC 4117", "first_name"=>"James"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Myers_March09.jpg", "title"=>"Professor", "last_name"=>"Myers", "room"=>"NSH 3517", "first_name"=>"Brad"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/neuwirth.web.2009.jpg", "title"=>"Professor, English", "last_name"=>"Neuwirth", "room"=>"BH 145F", "first_name"=>"Christine"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Ogan+2011+photo.jpg.jpg", "title"=>"Postdoc", "last_name"=>"Ogan", "room"=>"", "first_name"=>"Amy"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Paulos_March09.jpg", "title"=>"Assistant Professor", "last_name"=>"Paulos", "room"=>"NSH 3612E", "first_name"=>"Eric"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Rose_March09.jpg", "title"=>"Assistant Professor, HCII and Language Technologies Institute", "last_name"=>"Rose", "room"=>"NSH 4531", "first_name"=>"Carolyn Penstein"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/scheines_0.jpg", "title"=>"Professor, Head of Philosophy Dept.", "last_name"=>"Scheines", "room"=>"BH 135", "first_name"=>"Richard"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/DanS_March09.jpg", "title"=>"Buhl University Professor of Computer Science and Electrical and Computer Engineering", "last_name"=>"P.", "room"=>"", "first_name"=>"Daniel"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/john.jpg", "title"=>"Systems Scientist", "last_name"=>"Stamper", "room"=>"NSH 2602L", "first_name"=>"John"},
{"level" => "faculty", "title"=>"Post Doctoral Fellow", "last_name"=>"Colleen", "room"=>"NSH 2614", "first_name"=>"H."},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/_MG_3055.jpg", "title"=>"Post Doctoral Fellow", "last_name"=>"Tunc-Pekkan", "room"=>"NSH 2602B", "first_name"=>"Zelha"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/waibel_small-2.jpg", "title"=>"Professor, Language Technologies Institute", "last_name"=>"Waibel", "room"=>"NSH 2602C", "first_name"=>"Alexander"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/HCII_Yudelson_130.jpg", "title"=>"Post Doctoral Fellow", "last_name"=>"Yudelson", "room"=>"NSH 2602K", "first_name"=>"Michael"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Zimmerman_March09.jpg", "title"=>"Associate Professor", "last_name"=>"Zimmerman", "room"=>"NSH 2504F", "first_name"=>"John"}])
=======
Person.create({"Last"=>"Aleven", "Office"=>"NSH 3613", "Title"=>"Assistant Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Aleven_March09.jpg", "level"=>"faculty", "First"=>"Vincent"},
{"Last"=>"Anderson", "Office"=>"BH 345D", "Title"=>"Richard King Mellon University Professor of Psychology and Computer Science", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/anderson.jpg", "level"=>"faculty", "First"=>"John"},
{"Last"=>"Atkeson", "Office"=>"NSH A527", "Title"=>"Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/atkeson2.jpg", "level"=>"faculty", "First"=>"Chris"},
{"Last"=>"Cassell", "Office"=>"NSH 3519", "Title"=>"HCII Director", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Cassell_184_0.jpg", "level"=>"faculty", "First"=>"Justine"},
{"Last"=>"Corbett", "Office"=>"NSH 3605", "Title"=>"Associate Research Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Corbett_March09.jpg", "level"=>"faculty", "First"=>"Albert"},
{"Last"=>"Dabbish", "Office"=>"HbH 2109C", "Title"=>"Assistant Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/dabbish2.jpg", "level"=>"faculty", "First"=>"Laura"},
{"Last"=>"Date", "Office"=>"300 S. Craig Street Suite 228", "Title"=>"Director of MHCI", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/20090320_DSC_0006.jpg", "level"=>"faculty", "First"=>"Jenna"},
{"Last"=>"Davidoff", "Office"=>"NSH 2502", "Title"=>"Post Doctoral Fellow", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/davidoff-portrait-square.low-res.jpg", "level"=>"faculty", "First"=>"Scott"},
{"Last"=>"Dey", "Office"=>"NSH 2502C", "Title"=>"Associate Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Dey_March09.jpg", "level"=>"faculty", "First"=>"Anind"},
{"Last"=>"Dow", "Office"=>"NSH 3615", "Title"=>"Assistant Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/clip_image001.jpg", "level"=>"faculty", "First"=>"Steven"},
{"Last"=>"Farzan", "Office"=>"2504B NSH", "Title"=>"Post Doctoral Fellow", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/03-l.jpg", "level"=>"faculty", "First"=>"Rosta"},
{"Last"=>"Faste", "Office"=>"NSH 3527", "Title"=>"Visiting Assistant Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/haakon_for_cmu_web.png", "level"=>"faculty", "First"=>"Haakon"},
{"Last"=>"Forlizzi", "Office"=>"NSH 2504E", "Title"=>"A. Nico Habermann Associate Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Forlizzi_March09.jpg", "level"=>"faculty", "First"=>"Jodi"},
{"Last"=>"Hong", "Office"=>"NSH 3523", "Title"=>"Assistant Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Hong_March09.jpg", "level"=>"faculty", "First"=>"Jason"},
{"Last"=>"Hudson", "Office"=>"NSH 2502C", "Title"=>"Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Hudson_March09.jpg", "level"=>"faculty", "First"=>"Scott"},
{"Last"=>"John", "Office"=>"NSH 3521", "Title"=>"Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/John_March09.jpg", "level"=>"faculty", "First"=>"Bonnie"},
{"Last"=>"Kam", "Office"=>"NSH 3525", "Title"=>"Assistant Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Kam_March09.jpg", "level"=>"faculty", "First"=>"Matthew"},
{"Last"=>"Kiesler", "Office"=>"NSH 3513", "Title"=>"Hillman Professor of Computer Science and Human-Computer Interaction", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/SIGCHI_Kiesler.jpg", "level"=>"faculty", "First"=>"Sara"},
{"Last"=>"Kim", "Office"=>"417 SCRG, room # 306", "Title"=>"Post Doctoral Fellow", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Picture+182.jpg", "level"=>"faculty", "First"=>"SeungJun"},
{"Last"=>"Kittur", "Office"=>"NSH 2504 D", "Title"=>"Assistant Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/kittur.jpg", "level"=>"faculty", "First"=>"Aniket"},
{"Last"=>"Klatzky", "Office"=>"BH 346C", "Title"=>"Professor, Psychology Dept. and Center for the Neural Basis of Cognition", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Klatzky_March09.jpg", "level"=>"faculty", "First"=>"Roberta"},
{"Last"=>"Koedinger", "Office"=>"NSH 3601", "Title"=>"Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/ken010.jpg", "level"=>"faculty", "First"=>"Ken"},
{"Last"=>"Kraut", "Office"=>"NSH 3515", "Title"=>"Herbert A. Simon Professor of Human-Computer Interaction", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/bob-1-2006-crop4_0.jpg", "level"=>"faculty", "First"=>"Robert"},
{"Last"=>"Lindqvist", "Office"=>"NSH 2602 West", "Title"=>"Post Doctoral Fellow", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/HCIIface2.jpg", "level"=>"faculty", "First"=>"Janne"},
{"Last"=>"Mankoff", "Office"=>"Jen&#039;s Office: NSH 2405A", "Title"=>"Associate Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Mankoff_March09.jpg", "level"=>"faculty", "First"=>"Jennifer"},
{"Last"=>"Matsuda", "Office"=>"NSH 2619", "Title"=>"Systems Scientist", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/20090314_HCII.jpg", "level"=>"faculty", "First"=>"Noboru"},
{"Last"=>"McLaren", "Office"=>"NSH 2602 I", "Title"=>"Senior Systems Scientist", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/20090413-DSC_0196.jpg", "level"=>"faculty", "First"=>"Bruce"},
{"Last"=>"Morris", "Office"=>"GHC 4117", "Title"=>"Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/morris-03-2009.jpg", "level"=>"faculty", "First"=>"James"},
{"Last"=>"Myers", "Office"=>"NSH 3517", "Title"=>"Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Myers_March09.jpg", "level"=>"faculty", "First"=>"Brad"},
{"Last"=>"Neuwirth", "Office"=>"BH 145F", "Title"=>"Professor, English", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/neuwirth.web.2009.jpg", "level"=>"faculty", "First"=>"Christine"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Ogan+2011+photo.jpg.jpg", "Title"=>"Postdoc", "Last"=>"Ogan", "level"=>"faculty", "First"=>"Amy"},
{"Last"=>"Paulos", "Office"=>"NSH 3612E", "Title"=>"Assistant Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Paulos_March09.jpg", "level"=>"faculty", "First"=>"Eric"},
{"Last"=>"Ros√©", "Office"=>"NSH 4531", "Title"=>"Assistant Professor, HCII and Language Technologies Institute", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Rose_March09.jpg", "level"=>"faculty", "First"=>"Carolyn"},
{"Last"=>"Scheines", "Office"=>"BH 135", "Title"=>"Professor, Head of Philosophy Dept.", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/scheines_0.jpg", "level"=>"faculty", "First"=>"Richard"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/DanS_March09.jpg", "Title"=>"Buhl University Professor of Computer Science and Electrical and Computer Engineering", "Last"=>"Siewiorek", "level"=>"faculty", "First"=>"Daniel"},
{"Last"=>"Stamper", "Office"=>"NSH 2602L", "Title"=>"Systems Scientist", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/john.jpg", "level"=>"faculty", "First"=>"John"},
{"level"=>"faculty", "Title"=>"Post Doctoral Fellow", "Last"=>"Stuart", "Office"=>"NSH 2614", "First"=>"H."},
{"Last"=>"Tunc-Pekkan", "Office"=>"NSH 2602B", "Title"=>"Post Doctoral Fellow", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/_MG_3055.jpg", "level"=>"faculty", "First"=>"Zelha"},
{"Last"=>"Waibel", "Office"=>"NSH 2602C", "Title"=>"Professor, Language Technologies Institute", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/waibel_small-2.jpg", "level"=>"faculty", "First"=>"Alexander"},
{"Last"=>"Yudelson", "Office"=>"NSH 2602K", "Title"=>"Post Doctoral Fellow", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/HCII_Yudelson_130.jpg", "level"=>"faculty", "First"=>"Michael"},
{"Last"=>"Zimmerman", "Office"=>"NSH 2504F", "Title"=>"Associate Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Zimmerman_March09.jpg", "level"=>"faculty", "First"=>"John"},
{"Last"=>"Baskinger", "Office"=>"MM207D", "Title"=>"Associate Professor of Industrial Design", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/hcii_square.jpg", "level"=>"faculty", "First"=>"Mark"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/LenBass.jpg", "Title"=>"Senior Member of Technical Staff", "Last"=>"Bass", "level"=>"faculty", "First"=>"Len"},
{"level"=>"faculty", "Title"=>"Faculty, Entertainment Technology Center", "Last"=>"Blaine", "First"=>"Tina"},
{"Last"=>"Boyarski", "Office"=>"MM 110", "Title"=>"Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/Boyarski.web.2009.jpg", "level"=>"faculty", "First"=>"Daniel"},
{"Last"=>"Brusilovsky", "Office"=>"704 IS Building, 135 N. Bellefield", "Title"=>"Associate Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/brusilovsky-llbean.jpg", "level"=>"faculty", "First"=>"Peter"},
{"Last"=>"Christel", "Office"=>"PTC 3101", "Title"=>"Research Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/Mike_2008.png", "level"=>"faculty", "First"=>"Mike"},
{"Last"=>"Cranor", "Office"=>"CIC 2207", "Title"=>"Associate Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/lorrie-headshot.jpg", "level"=>"faculty", "First"=>"Lorrie"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/Dannenberg_small.jpg", "Title"=>"Senior Research Computer Scientist, School of Computer Science", "Last"=>"Dannenberg", "level"=>"faculty", "First"=>"Roger"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/MEskenazi.jpg", "Title"=>"Systems Scientist, Language Technologies Institute", "Last"=>"Eskenazi", "level"=>"faculty", "First"=>"Maxine"},
{"Last"=>"Fahlman", "Office"=>"Wean 8214", "Title"=>"Research Professor", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/SEF2007-small.jpg", "level"=>"faculty", "First"=>"Scott"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/c-gonzalez.jpg", "Title"=>"Associate Research Professor and Director, DDMLab, Social and Decision Sciences Department", "Last"=>"Gonzalez", "level"=>"faculty", "First"=>"Cleotilde"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/gross_small.jpg", "Title"=>"Professor, Computational Design, School of Architecture", "Last"=>"Gross", "level"=>"faculty", "First"=>"Mark"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/herbsleb.jpg", "Title"=>"Professor, School of Computer Science, Director, Software Industry Center", "Last"=>"Herbsleb", "level"=>"faculty", "First"=>"James"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/Hodgins_Jessica.jpg", "Title"=>"Professor, Robotics Institute", "Last"=>"Hodgins", "level"=>"faculty", "First"=>"Jessica"},
{"level"=>"faculty", "Title"=>"Assistant Professor, Psychology Dept.", "Last"=>"Holt", "First"=>"Lori"},
{"Last"=>"Jones", "Office"=>"BH367", "Title"=>"Teaching Professor of French and Computer-Assisted Language Learning", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/jones.jpg", "level"=>"faculty", "First"=>"Christopher"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/TKanade.jpg", "Title"=>"Professor, Robotics Institute, Computer Science Department", "Last"=>"Kanade", "level"=>"faculty", "First"=>"Takeo"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/DavidKaufer.jpg", "Title"=>"Head, English Dept.", "Last"=>"Kaufer", "level"=>"faculty", "First"=>"David"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/SamLeinhardt.jpg", "Title"=>"President and CEO, Penthera Technologies, Inc.", "Last"=>"Leinhardt", "level"=>"faculty", "First"=>"Samuel"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/PLucas.jpg", "Title"=>"CEO, MAYA Design Group, Inc.", "Last"=>"Lucas", "level"=>"faculty", "First"=>"Peter"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/DMarinelli.jpg", "Title"=>"Co-Director, Entertainment Technology Center", "Last"=>"Marinelli", "level"=>"faculty", "First"=>"Don"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/RMartin.jpg", "Title"=>"Adjunct Principal Systems Scientist, Robotics Institute", "Last"=>"Martin", "level"=>"faculty", "First"=>"Richard"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/RMaxion.jpg", "Title"=>"Principal Systems Scientist, Computer Science Dept.", "Last"=>"Maxion", "level"=>"faculty", "First"=>"Roy"},
{"level"=>"faculty", "Title"=>"Visiting Assistant Professor", "Last"=>"Miller", "First"=>"Jill"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/TomMitchell.jpg", "Title"=>"Fredkin Professor of AI and Learning, Director, Center for Automated Learning and Discovery (CALD)", "Last"=>"Mitchell", "level"=>"faculty", "First"=>"Tom"},
{"Last"=>"Mostow", "Office"=>"NSH 4103", "Title"=>"Research Professor, Robotics Institute, Language Technologies Institute, HCII, Center for Automated Learning and Discovery, PIER", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/Mostow_J.jpg", "level"=>"faculty", "First"=>"Jack"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/RajReddy.jpg", "Title"=>"Simon University Professor, School of Computer Science", "Last"=>"Reddy", "level"=>"faculty", "First"=>"Raj"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/LReder.jpg", "Title"=>"Professor, Psychology", "Last"=>"Reder", "level"=>"faculty", "First"=>"Lynne"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/RRosenfeld.jpg", "Title"=>"Professor, LTI, CALD, CSD", "Last"=>"Rosenfeld", "level"=>"faculty", "First"=>"Roni"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/ARudnicky.jpg", "Title"=>"Senior Systems Scientist, Computer Science Dept.", "Last"=>"Rudnicky", "level"=>"faculty", "First"=>"Alexander"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/rummel.jpg", "Title"=>"Professor, Educational Psychology, Ruhr-Universitat Bochum, Germany", "Last"=>"Rummel", "level"=>"faculty", "First"=>"Nikol"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/Norman+Sadeh_Locaccino_Web_low_res.jpg", "Title"=>"Professor, School of Computer Science", "Last"=>"Sadeh", "level"=>"faculty", "First"=>"Norman"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/Jesse_Schell.jpg", "Title"=>"Assistant Professor of the Practice, Entertainment Technology Center", "Last"=>"Schell", "level"=>"faculty", "First"=>"Jesse"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/BillScherlis.jpg", "Title"=>"Principal Research Scientist, Director, Information Technology Center", "Last"=>"Scherlis", "level"=>"faculty", "First"=>"William"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/MaryShaw.jpg", "Title"=>"J. Perlis Professor, Computer Science Dept.", "Last"=>"Shaw", "level"=>"faculty", "First"=>"Mary"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/MelSiegel.jpg", "Title"=>"Associate Research Professor, Robotics Institute", "Last"=>"Siegel", "level"=>"faculty", "First"=>"Mel"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/ScottStevens.jpg", "Title"=>"Senior Systems Scientist, ETC, HCII", "Last"=>"Stevens", "level"=>"faculty", "First"=>"Scott"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/straus_susan.18.150.jpg", "Title"=>"Adjunct Associate Professor, Behavioral Scientist, RAND", "Last"=>"Straus", "level"=>"faculty", "First"=>"Susan"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/KatiaSycara.jpg", "Title"=>"Principal Research Scientist, Robotics Institute", "Last"=>"Sycara", "level"=>"faculty", "First"=>"Katia"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/AlonsoVera.jpg", "Title"=>"Adjunct Associate Research Scientist, Carnegie Mellon West", "Last"=>"Vera", "level"=>"faculty", "First"=>"Alonso"},
{"level"=>"faculty", "Last"=>"vonAhn", "First"=>"Luis"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/20090319_DSC_1003+more+awake.png", "level"=>"phd", "Last"=>"Aleahmad", "Office"=>"NSH 3603", "First"=>"Turadg"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/20090220_DSC_0136.jpg", "level"=>"phd", "Last"=>"Balakrishnan", "First"=>"Aruna"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/20090220_DSC_0144.jpg", "level"=>"phd", "Last"=>"Burke", "Office"=>"300 S. Craig St., Room 206", "First"=>"Moira"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/cropped+Chang+F10+F10+Kerrys+first+choice+for+web+DSC_4592.jpg", "level"=>"phd", "Last"=>"Chang", "Office"=>"NSH 4611", "First"=>"Kerry"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/tawanna.jpg", "level"=>"phd", "Last"=>"Dillahunt", "Office"=>"NSH 4619", "First"=>"Tawanna"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/chloe.jpg", "level"=>"phd", "Last"=>"Fan", "Office"=>"NSH 4606", "First"=>"Chloe"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/cropped+Gulotta+F10+photo+DSC_4650.jpg", "level"=>"phd", "Last"=>"Gulotta", "Office"=>"NSH 4609", "First"=>"Rebecca"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/20090305_DSC_0571.jpg", "level"=>"phd", "Last"=>"Gweon", "First"=>"Gahgene"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/20090319_DSC_0993.jpg", "level"=>"phd", "Last"=>"Harrison", "Office"=>"NSH 3612", "First"=>"Chris"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/eiji3.jpg", "level"=>"phd", "Last"=>"Hayashi", "First"=>"Eiji"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/20090306_DSC_0681.jpg", "level"=>"phd", "Last"=>"Howley", "First"=>"Iris"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/kevin.jpg", "level"=>"phd", "Last"=>"Huang", "First"=>"Kevin"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/Kang+F10+cropped+photo+DSC_5421.jpg", "level"=>"phd", "Last"=>"Kang", "Office"=>"NSH 4617", "First"=>"Ruogu"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/20090319_DSC_1042.jpg", "level"=>"phd", "Last"=>"Kim", "Office"=>"NSH 2502", "First"=>"Sunyoung"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/Kinnaird+F10+DSC_4752_0.jpg", "level"=>"phd", "Last"=>"Kinnaird", "Office"=>"NSH 4617", "First"=>"Peter"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/anuj.jpg", "level"=>"phd", "Last"=>"Kumar", "Office"=>"NSH 3611", "First"=>"Anuj"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/staceyk.jpg", "level"=>"phd", "Last"=>"Kuznetsov", "First"=>"Stacey"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/mattlee.jpg", "level"=>"phd", "Last"=>"Lee", "Office"=>"NSH 4607", "First"=>"Matthew"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/HCII_MinKyungLee.jpg", "level"=>"phd", "Last"=>"Lee", "First"=>"Min"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/cropped+Li+Ian+preF06.jpg", "level"=>"phd", "Last"=>"Li", "First"=>"Ian"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/brianlim.jpg", "level"=>"phd", "Last"=>"Lim", "Office"=>"NSH 4619", "First"=>"Brian"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/website-20090820_124617.jpg", "level"=>"phd", "Last"=>"Lomas", "Office"=>"NSH 4611", "First"=>"James"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/cropped+Yanjin+Long+F10+photo+DSC_4605.jpg", "level"=>"phd", "Last"=>"Long", "Office"=>"NSH 4611", "First"=>"Yanjin"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/Gabi+Marcu+photo+July+2009.PNG", "level"=>"phd", "Last"=>"Marcu", "Office"=>"NSH 4617", "First"=>"Gabriela"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/HCI_headshot.jpg", "level"=>"phd", "Last"=>"Marlow", "First"=>"Jennifer"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/will.jpg", "level"=>"phd", "Last"=>"Odom", "Office"=>"NSH 3611", "First"=>"Will"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/20090220_DSC_0034.jpg", "level"=>"phd", "Last"=>"Oney", "First"=>"Stephen"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/cropped+James+Pierce.jpg", "level"=>"phd", "Last"=>"Pierce", "First"=>"James"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/martina.jpg", "level"=>"phd", "Last"=>"Rau", "First"=>"Martina"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/croppedRzeszotarski+F10+DSC_4658.jpg", "level"=>"phd", "Last"=>"Rzeszotarski", "Office"=>"NSH 4609", "First"=>"Jeffrey"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/julia.jpg", "level"=>"phd", "Last"=>"Schwarz", "First"=>"Julia"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/cropped+Stampfer+F10+photo+DSC_4631.jpg", "level"=>"phd", "Last"=>"Stampfer", "Office"=>"NSH 4609", "First"=>"Eliane"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/jason-300kb-square.jpg", "level"=>"phd", "Last"=>"Wiese", "Office"=>"Newell Simon Hall 3603", "First"=>"Jason"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/20090319_DSC_0926.jpg", "level"=>"phd", "Last"=>"Wylie", "First"=>"Ruth"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/HaiyiZhu3.jpg", "level"=>"phd", "Last"=>"Zhu", "Office"=>"NSH 4606", "First"=>"Haiyi"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-26.jpg", "level"=>"masters", "Last"=>"Andrianoff", "First"=>"Timothy"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-78.jpg", "level"=>"masters", "Last"=>"Auw", "First"=>"Christie"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-06.jpg", "level"=>"masters", "Last"=>"Awori", "First"=>"Kagonya"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-20.jpg", "level"=>"masters", "Last"=>"Bai", "First"=>"Julie"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-145.jpg", "level"=>"masters", "Last"=>"Bariola", "First"=>"Pablo"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-44.jpg", "level"=>"masters", "Last"=>"Caravelli", "First"=>"Paul"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-153.jpg", "level"=>"masters", "Last"=>"Chandra", "First"=>"Hitee"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-117.jpg", "level"=>"masters", "Last"=>"Chatterji", "First"=>"Vikram"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-110.jpg", "level"=>"masters", "Last"=>"Chi", "First"=>"Chung-Yi"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-51.jpg", "level"=>"masters", "Last"=>"Chua", "First"=>"Chong"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-15.jpg", "level"=>"masters", "Last"=>"Clark", "First"=>"Emily"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-138.jpg", "level"=>"masters", "Last"=>"Coelho", "First"=>"Paulo"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-136.jpg", "level"=>"masters", "Last"=>"Dudiak", "First"=>"Eric"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-88.jpg", "level"=>"masters", "Last"=>"Effner", "First"=>"Troy"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-38.jpg", "level"=>"masters", "Last"=>"Fang", "First"=>"Zhenshuo"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-05.jpg", "level"=>"masters", "Last"=>"Fernandez", "First"=>"Nicole"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-132.jpg", "level"=>"masters", "Last"=>"Flowers", "First"=>"John"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-22.jpg", "level"=>"masters", "Last"=>"Freitas", "First"=>"Daniel"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-114.jpg", "level"=>"masters", "Last"=>"Ganesan", "First"=>"Arun"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/AndrewGillespie_photo.jpg", "level"=>"masters", "Last"=>"Gillespie", "First"=>"Drew"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-28.jpg", "level"=>"masters", "Last"=>"Giraldo", "First"=>"Mauricio"},
{"level"=>"masters", "Last"=>"Gon√ßalves", "First"=>"Andreia"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-64.jpg", "level"=>"masters", "Last"=>"Gotow", "First"=>"J."},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-48.jpg", "level"=>"masters", "Last"=>"Gupta", "First"=>"Bhavana"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-47.jpg", "level"=>"masters", "Last"=>"Gupta", "First"=>"Sanchit"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-33.jpg", "level"=>"masters", "Last"=>"Holtzblatt", "First"=>"Shoshana"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-107.jpg", "level"=>"masters", "Last"=>"Horstman", "First"=>"John"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/Jain.jpg", "level"=>"masters", "Last"=>"Jain", "First"=>"Anubhuti"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/brendan+kiu.jpg", "level"=>"masters", "Last"=>"Kiu", "First"=>"Brendan"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-12.jpg", "level"=>"masters", "Last"=>"Kurani", "First"=>"Nisha"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-17.jpg", "level"=>"masters", "Last"=>"Lee", "First"=>"Jooyong"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-128.jpg", "level"=>"masters", "Last"=>"Lin", "First"=>"Clifton"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-36.jpg", "level"=>"masters", "Last"=>"Lin", "First"=>"Honray"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/square_IMG_7332-1-1.jpg", "level"=>"masters", "Last"=>"Lin", "First"=>"Susan"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-127.jpg", "level"=>"masters", "Last"=>"Luong", "First"=>"Raymond"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-144.jpg", "level"=>"masters", "Last"=>"Ma", "First"=>"Cong"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-151.jpg", "level"=>"masters", "Last"=>"Martins", "First"=>"Maria"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-97.jpg", "level"=>"masters", "Last"=>"Micklin", "First"=>"Claire"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-73.jpg", "level"=>"masters", "Last"=>"Mulholland", "First"=>"James"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-43.jpg", "level"=>"masters", "Last"=>"Nagda", "First"=>"Mehwish"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-13.jpg", "level"=>"masters", "Last"=>"Ng", "First"=>"Tiffany"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/mollynix.jpg", "level"=>"masters", "Last"=>"Nix", "First"=>"Molly"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-74.jpg", "level"=>"masters", "Last"=>"Paepcke", "First"=>"Stephanie"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-98.jpg", "level"=>"masters", "Last"=>"Pan", "First"=>"Alan"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-02.jpg", "level"=>"masters", "Last"=>"Park", "First"=>"Angela"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-29.jpg", "level"=>"masters", "Last"=>"Penney", "First"=>"Ward"},
{"level"=>"masters", "Last"=>"Poor", "First"=>"Tony"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-56.jpg", "level"=>"masters", "Last"=>"Pryor", "First"=>"Jared"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/preethi_raju_pic.png", "level"=>"masters", "Last"=>"Raju", "First"=>"Preethi"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-133.jpg", "level"=>"masters", "Last"=>"Ramasubramanian", "First"=>"Sriram"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-141.jpg", "level"=>"masters", "Last"=>"Randall", "First"=>"David"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-70.jpg", "level"=>"masters", "Last"=>"Rivard", "First"=>"Kathryn"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-54.jpg", "level"=>"masters", "Last"=>"Savage", "First"=>"Trevor"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-87.jpg", "level"=>"masters", "Last"=>"Schwartzman", "First"=>"Emily"},
{"level"=>"masters", "Last"=>"Shon", "First"=>"Eva"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-108.jpg", "level"=>"masters", "Last"=>"Shuster", "First"=>"Mark"},
{"level"=>"masters", "Last"=>"Sugarman", "First"=>"Spencer"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-25.jpg", "level"=>"masters", "Last"=>"Tan", "First"=>"Nastasha"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-82.jpg", "level"=>"masters", "Last"=>"Vandy", "First"=>"Sypraseuth"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-40.jpg", "level"=>"masters", "Last"=>"Verma", "First"=>"Namrata"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-08.jpg", "level"=>"masters", "Last"=>"Wang", "First"=>"Yuan"},
{"Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-124.jpg", "level"=>"masters", "Last"=>"Yang", "First"=>"Ya-Chun"},
{"level"=>"masters", "Last"=>"Zhang", "First"=>"Anthony"},
{"level"=>"staff", "Title"=>"Administrative Associate", "Last"=>"Homyak", "Office"=>"3501B", "First"=>"Alex"},
{"Last"=>"Bodnar", "Office"=>"NSH 3526", "Title"=>"Administrative Associate", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/web.photo.2009_0.jpg", "level"=>"staff", "First"=>"Jo"},
{"Last"=>"Carrozza", "Office"=>"NSH 3507", "Title"=>"Assistant Business Manager", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/mlc_0.jpg", "level"=>"staff", "First"=>"Melissa"},
{"Last"=>"Casillas", "Office"=>"NSH 3526", "Title"=>"Administrative Associate", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/David+Casillas-1.jpg", "level"=>"staff", "First"=>"David"},
{"Last"=>"D&#039;Amico", "Office"=>"NSH 4527", "Title"=>"Project Manager", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/web.photo.2009.jpg", "level"=>"staff", "First"=>"Marian"},
{"Last"=>"Gittleman", "Office"=>"NSH 3521", "Title"=>"Manager, Director&#039;s Office", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/Michele+small+picture.jpg", "level"=>"staff", "First"=>"Michele"},
{"level"=>"staff", "Title"=>"Administrative Coordinator", "Last"=>"King", "Office"=>"NSH 3526", "First"=>"Rebecca"},
{"Last"=>"Kravitz", "Office"=>"NSH 4615", "Title"=>"Graduate Program Coordinator", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/Queenie+F10+photo+DSC_4583.jpg", "level"=>"staff", "First"=>"Queenie"},
{"level"=>"staff", "Title"=>"Business Manager", "Last"=>"Murrin-Macey", "Office"=>"NSH 3511", "First"=>"Denise"},
{"Last"=>"Scott", "Office"=>"NSH 3509", "Title"=>"Office Staff III", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/web.photo.2009_1.jpg", "level"=>"staff", "First"=>"Mary"},
{"Last"=>"Stanley", "Office"=>"300 SCRG Rm. 208", "Title"=>"Program Assistant", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/J.+Stanley+Headshot_small.jpg", "level"=>"staff", "First"=>"Jessica"},
{"Last"=>"Szegedy", "Office"=>"NSH 3526", "Title"=>"Administrative Coordinator and HCII Undergraduate Program Coordinator", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/photo_0.JPG", "level"=>"staff", "First"=>"Indra"},
{"Last"=>"Vento", "Office"=>"NSH 3509", "Title"=>"Research Administrator", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/OB2N9191_1.jpg", "level"=>"staff", "First"=>"Lisa"},
{"Last"=>"Willis", "Office"=>"300 SCRG Rm. 229", "Title"=>"Academic Program Coordinator", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/ME.jpg", "level"=>"staff", "First"=>"Nicole"},
{"level"=>"staff", "Title"=>"Managing Director, PSLC", "Last"=>"Bett", "Office"=>"NSH 2602I", "First"=>"Michael"},
{"level"=>"staff", "Title"=>"Research Assistant", "Last"=>"Brooks", "First"=>"Maria"},
{"Last"=>"Carvalho", "Office"=>"NSH 2602H", "Title"=>"Research Associate", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/adriana.jpg", "level"=>"staff", "First"=>"Adriana"},
{"Last"=>"Chang", "Office"=>"NSH 2620C", "Title"=>"Senior Research Programmer", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/Chang.jpg", "level"=>"staff", "First"=>"Chang-Hsin"},
{"level"=>"staff", "Title"=>"Research Programmer", "Last"=>"Cheng", "Office"=>"NSH 2620A", "First"=>"Hui"},
{"level"=>"staff", "Title"=>"Senior Research Programmer", "Last"=>"Cosgrove", "Office"=>"GHC 4007", "First"=>"Dennis"},
{"level"=>"staff", "Title"=>"Senior Research Programmer", "Last"=>"Culyba", "Office"=>"GHC 4007", "First"=>"David"},
{"Last"=>"Demi", "Office"=>"NSH 2602J", "Title"=>"Senior Research Programmer", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/sdemi.jpg", "level"=>"staff", "First"=>"Sandra"},
{"level"=>"staff", "Title"=>"Research Assistant", "Last"=>"Emerson", "Office"=>"NSH 2602", "First"=>"Eric"},
{"Last"=>"Faulring", "Office"=>"417 SCRG 302B", "Title"=>"Research Programmer", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/Andrew+Faulring_0.jpg", "level"=>"staff", "First"=>"Andrew"},
{"level"=>"staff", "Title"=>"Research Programmer", "Last"=>"Keiser", "Office"=>"NSH 2602A", "First"=>"Victoria"},
{"Last"=>"Kusbit", "Office"=>"NSH 2619", "Title"=>"PSLC Research Manager", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/gkusbit.jpg", "level"=>"staff", "First"=>"Gail"},
{"Last"=>"Leber", "Office"=>"NSH 2602J", "Title"=>"Documentation Specialist", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/portrait-20090319_DSC_0919-250px.png", "level"=>"staff", "First"=>"Brett"},
{"level"=>"staff", "Title"=>"Research Assistant", "Last"=>"Luo", "First"=>"Rosemary"},
{"Last"=>"MacLaren", "Office"=>"NSH 2620B", "Title"=>"Senior Research Programmer", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/BenMacLaren.jpg", "level"=>"staff", "First"=>"Ben"},
{"level"=>"staff", "Title"=>"Research Associate", "Last"=>"McLaughlin", "Office"=>"NSH 2620A", "First"=>"Elizabeth"},
{"Last"=>"Morrison", "Office"=>"300 SCRG 203", "Title"=>"Senior Research Programmer", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/morrison.jpg", "level"=>"staff", "First"=>"Don"},
{"level"=>"staff", "Title"=>"Systems/Software Associate", "Last"=>"Ojeda", "Office"=>"NSH 2504B", "First"=>"Marcos"},
{"level"=>"staff", "Title"=>"Research Programmer", "Last"=>"Popescu", "Office"=>"NSH 2612", "First"=>"Octav"},
{"level"=>"staff", "Title"=>"Research Programmer", "Last"=>"Raizada", "Office"=>"NSH 2602A", "First"=>"Rohan"},
{"level"=>"staff", "Title"=>"Research Programmer", "Last"=>"Rojas", "Office"=>"NSH 2502", "First"=>"Julian"},
{"level"=>"staff", "Title"=>"Research Programmer", "Last"=>"Ringenberg", "Office"=>"NSH 2602B", "First"=>"Michael"},
{"level"=>"staff", "Title"=>"Research Assistant", "Last"=>"Schreiber", "Office"=>"NSH 2602B", "First"=>"Abraham"},
{"Last"=>"Sewall", "Office"=>"NSH 2617", "Title"=>"Project Director", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/Sewall_small.jpg", "level"=>"staff", "First"=>"Jonathan"},
{"Last"=>"Skogsholm", "Office"=>"NSH 2602J", "Title"=>"PSLC DataShop Manager", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/HCII+Photos+%28No+MHCI%29_Page_048.jpg", "level"=>"staff", "First"=>"Alida"},
{"level"=>"staff", "Title"=>"Software Engineer", "Last"=>"Springfield", "Office"=>"NSH 2504, EDSH 234", "First"=>"James"},
{"level"=>"staff", "Title"=>"Research Assistant", "Last"=>"Tassini", "Office"=>"NSH 2502B", "First"=>"Kevin"},
{"level"=>"staff", "Title"=>"Research Programmer", "Last"=>"Thompson", "Office"=>"NSH 2504", "First"=>"Robert"},
{"Last"=>"Velsen", "Office"=>"NSH 2619", "Title"=>"Research Programmer", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/Van_Velsen_Martin.JPG", "level"=>"staff", "First"=>"Martin"},
{"Last"=>"Wagner", "Office"=>"NSH 2620B", "Title"=>"Research Associate II", "Image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/Wagner.jpg", "level"=>"staff", "First"=>"Angela"},
{"level"=>"staff", "Title"=>"Research Associate", "Last"=>"Watson", "Office"=>"NSH 2602G", "First"=>"Shayna"},
{"level"=>"staff", "Title"=>"Research Associate", "Last"=>"Yarzebinski", "Office"=>"NSH 2602", "First"=>"Evelyn"},
{"level"=>"staff", "Title"=>"Systems Support Specialist", "Last"=>"Yu", "Office"=>"GHC 4007", "First"=>"Gabriel"},
{"level"=>"staff", "Title"=>"Sr. Research Programmer", "Last"=>"Yu", "Office"=>"NSH 2602G", "First"=>"Shanwen"},
)
>>>>>>> Updated scraped data to include everyone, not just faculty
