# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)

Person.create([{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Aleven_March09.jpg", "title"=>"Assistant Professor", "last_name"=>"Aleven", "room"=>"NSH 3613", "first_name"=>"Vincent"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/anderson.jpg", "title"=>"Richard King Mellon University Professor of Psychology and Computer Science", "last_name"=>"Anderson", "room"=>"BH 345D", "first_name"=>"John"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/atkeson2.jpg", "title"=>"Professor", "last_name"=>"Atkeson", "room"=>"NSH A527", "first_name"=>"Chris"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Cassell_184_0.jpg", "title"=>"HCII Director", "last_name"=>"Cassell", "room"=>"NSH 3519", "first_name"=>"Justine"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Corbett_March09.jpg", "title"=>"Associate Research Professor", "last_name"=>"Corbett", "room"=>"NSH 3605", "first_name"=>"Albert"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/dabbish2.jpg", "title"=>"Assistant Professor", "last_name"=>"Dabbish", "room"=>"HbH 2109C", "first_name"=>"Laura"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/20090320_DSC_0006.jpg", "title"=>"Director of MHCI", "last_name"=>"Date", "room"=>"300 S. Craig Street Suite 228", "first_name"=>"Jenna"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/davidoff-portrait-square.low-res.jpg", "title"=>"Post Doctoral Fellow", "last_name"=>"Davidoff", "room"=>"NSH 2502", "first_name"=>"Scott"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Dey_March09.jpg", "title"=>"Associate Professor", "last_name"=>"Dey", "room"=>"NSH 2502C", "first_name"=>"Anind"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/clip_image001.jpg", "title"=>"Assistant Professor", "last_name"=>"Dow", "room"=>"NSH 3615", "first_name"=>"Steven"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/03-l.jpg", "title"=>"Post Doctoral Fellow", "last_name"=>"Farzan", "room"=>"2504B NSH", "first_name"=>"Rosta"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/haakon_for_cmu_web.png", "title"=>"Visiting Assistant Professor", "last_name"=>"Faste", "room"=>"NSH 3527", "first_name"=>"Haakon"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Forlizzi_March09.jpg", "title"=>"A. Nico Habermann Associate Professor", "last_name"=>"Forlizzi", "room"=>"NSH 2504E", "first_name"=>"Jodi"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Hong_March09.jpg", "title"=>"Assistant Professor", "last_name"=>"Hong", "room"=>"NSH 3523", "first_name"=>"Jason"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Hudson_March09.jpg", "title"=>"Professor", "last_name"=>"Hudson", "room"=>"NSH 2502C", "first_name"=>"Scott"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/John_March09.jpg", "title"=>"Professor", "last_name"=>"John", "room"=>"NSH 3521", "first_name"=>"Bonnie"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Kam_March09.jpg", "title"=>"Assistant Professor", "last_name"=>"Kam", "room"=>"NSH 3525", "first_name"=>"Matthew"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/SIGCHI_Kiesler.jpg", "title"=>"Hillman Professor of Computer Science and Human-Computer Interaction", "last_name"=>"Kiesler", "room"=>"NSH 3513", "first_name"=>"Sara"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Picture+182.jpg", "title"=>"Post Doctoral Fellow", "last_name"=>"Kim", "room"=>"417 SCRG, room # 306", "first_name"=>"SeungJun"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/kittur.jpg", "title"=>"Assistant Professor", "last_name"=>"Kittur", "room"=>"NSH 2504 D", "first_name"=>"Aniket"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Klatzky_March09.jpg", "title"=>"Professor, Psychology Dept. and Center for the Neural Basis of Cognition", "last_name"=>"Klatzky", "room"=>"BH 346C", "first_name"=>"Roberta"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/ken010.jpg", "title"=>"Professor", "last_name"=>"Koedinger", "room"=>"NSH 3601", "first_name"=>"Ken"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/bob-1-2006-crop4_0.jpg", "title"=>"Herbert A. Simon Professor of Human-Computer Interaction", "last_name"=>"Kraut", "room"=>"NSH 3515", "first_name"=>"Robert"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/HCIIface2.jpg", "title"=>"Post Doctoral Fellow", "last_name"=>"Lindqvist", "room"=>"NSH 2602 West", "first_name"=>"Janne"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Mankoff_March09.jpg", "title"=>"Associate Professor", "last_name"=>"Mankoff", "room"=>"Jen&#039;s room: NSH 2405A", "first_name"=>"Jennifer"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/20090314_HCII.jpg", "title"=>"Systems Scientist", "last_name"=>"Matsuda", "room"=>"NSH 2619", "first_name"=>"Noboru"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/20090413-DSC_0196.jpg", "title"=>"Senior Systems Scientist", "last_name"=>"M.", "room"=>"NSH 2602 I", "first_name"=>"Bruce"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/morris-03-2009.jpg", "title"=>"Professor", "last_name"=>"Morris", "room"=>"GHC 4117", "first_name"=>"James"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Myers_March09.jpg", "title"=>"Professor", "last_name"=>"Myers", "room"=>"NSH 3517", "first_name"=>"Brad"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/neuwirth.web.2009.jpg", "title"=>"Professor, English", "last_name"=>"Neuwirth", "room"=>"BH 145F", "first_name"=>"Christine"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Ogan+2011+photo.jpg.jpg", "title"=>"Postdoc", "last_name"=>"Ogan", "room"=>"", "first_name"=>"Amy"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Paulos_March09.jpg", "title"=>"Assistant Professor", "last_name"=>"Paulos", "room"=>"NSH 3612E", "first_name"=>"Eric"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Rose_March09.jpg", "title"=>"Assistant Professor, HCII and Language Technologies Institute", "last_name"=>"Rose", "room"=>"NSH 4531", "first_name"=>"Carolyn Penstein"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/scheines_0.jpg", "title"=>"Professor, Head of Philosophy Dept.", "last_name"=>"Scheines", "room"=>"BH 135", "first_name"=>"Richard"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/DanS_March09.jpg", "title"=>"Buhl University Professor of Computer Science and Electrical and Computer Engineering", "last_name"=>"P.", "room"=>"", "first_name"=>"Daniel"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/john.jpg", "title"=>"Systems Scientist", "last_name"=>"Stamper", "room"=>"NSH 2602L", "first_name"=>"John"},
{"level" => "faculty", "title"=>"Post Doctoral Fellow", "last_name"=>"Colleen", "room"=>"NSH 2614", "first_name"=>"H."},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/_MG_3055.jpg", "title"=>"Post Doctoral Fellow", "last_name"=>"Tunc-Pekkan", "room"=>"NSH 2602B", "first_name"=>"Zelha"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/waibel_small-2.jpg", "title"=>"Professor, Language Technologies Institute", "last_name"=>"Waibel", "room"=>"NSH 2602C", "first_name"=>"Alexander"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/HCII_Yudelson_130.jpg", "title"=>"Post Doctoral Fellow", "last_name"=>"Yudelson", "room"=>"NSH 2602K", "first_name"=>"Michael"},
{"level" => "faculty", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Zimmerman_March09.jpg", "title"=>"Associate Professor", "last_name"=>"Zimmerman", "room"=>"NSH 2504F", "first_name"=>"John"}])