# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)

Person.create([{"last_name"=>"Aleven", "room"=>"NSH 3613", "title"=>"Assistant Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Aleven_March09.jpg", "level"=>"faculty", "first_name"=>"Vincent"},
{"last_name"=>"Anderson", "room"=>"BH 345D", "title"=>"Richard King Mellon University Professor of Psychology and Computer Science", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/anderson.jpg", "level"=>"faculty", "first_name"=>"John"},
{"last_name"=>"Atkeson", "room"=>"NSH A527", "title"=>"Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/atkeson2.jpg", "level"=>"faculty", "first_name"=>"Chris"},
{"last_name"=>"Cassell", "room"=>"NSH 3519", "title"=>"HCII Director", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Cassell_184_0.jpg", "level"=>"faculty", "first_name"=>"Justine"},
{"last_name"=>"Corbett", "room"=>"NSH 3605", "title"=>"Associate Research Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Corbett_March09.jpg", "level"=>"faculty", "first_name"=>"Albert"},
{"last_name"=>"Dabbish", "room"=>"HbH 2109C", "title"=>"Assistant Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/dabbish2.jpg", "level"=>"faculty", "first_name"=>"Laura"},
{"last_name"=>"Date", "room"=>"300 S. Craig Street Suite 228", "title"=>"Director of MHCI", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/20090320_DSC_0006.jpg", "level"=>"faculty", "first_name"=>"Jenna"},
{"last_name"=>"Davidoff", "room"=>"NSH 2502", "title"=>"Post Doctoral Fellow", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/davidoff-portrait-square.low-res.jpg", "level"=>"faculty", "first_name"=>"Scott"},
{"last_name"=>"Dey", "room"=>"NSH 2502C", "title"=>"Associate Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Dey_March09.jpg", "level"=>"faculty", "first_name"=>"Anind"},
{"last_name"=>"Dow", "room"=>"NSH 3615", "title"=>"Assistant Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/clip_image001.jpg", "level"=>"faculty", "first_name"=>"Steven"},
{"last_name"=>"Farzan", "room"=>"2504B NSH", "title"=>"Post Doctoral Fellow", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/03-l.jpg", "level"=>"faculty", "first_name"=>"Rosta"},
{"last_name"=>"Faste", "room"=>"NSH 3527", "title"=>"Visiting Assistant Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/haakon_for_cmu_web.png", "level"=>"faculty", "first_name"=>"Haakon"},
{"last_name"=>"Forlizzi", "room"=>"NSH 2504E", "title"=>"A. Nico Habermann Associate Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Forlizzi_March09.jpg", "level"=>"faculty", "first_name"=>"Jodi"},
{"last_name"=>"Hong", "room"=>"NSH 3523", "title"=>"Assistant Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Hong_March09.jpg", "level"=>"faculty", "first_name"=>"Jason"},
{"last_name"=>"Hudson", "room"=>"NSH 2502C", "title"=>"Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Hudson_March09.jpg", "level"=>"faculty", "first_name"=>"Scott"},
{"last_name"=>"John", "room"=>"NSH 3521", "title"=>"Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/John_March09.jpg", "level"=>"faculty", "first_name"=>"Bonnie"},
{"last_name"=>"Kam", "room"=>"NSH 3525", "title"=>"Assistant Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Kam_March09.jpg", "level"=>"faculty", "first_name"=>"Matthew"},
{"last_name"=>"Kiesler", "room"=>"NSH 3513", "title"=>"Hillman Professor of Computer Science and Human-Computer Interaction", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/SIGCHI_Kiesler.jpg", "level"=>"faculty", "first_name"=>"Sara"},
{"last_name"=>"Kim", "room"=>"417 SCRG, room # 306", "title"=>"Post Doctoral Fellow", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Picture+182.jpg", "level"=>"faculty", "first_name"=>"SeungJun"},
{"last_name"=>"Kittur", "room"=>"NSH 2504 D", "title"=>"Assistant Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/kittur.jpg", "level"=>"faculty", "first_name"=>"Aniket"},
{"last_name"=>"Klatzky", "room"=>"BH 346C", "title"=>"Professor, Psychology Dept. and Center for the Neural Basis of Cognition", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Klatzky_March09.jpg", "level"=>"faculty", "first_name"=>"Roberta"},
{"last_name"=>"Koedinger", "room"=>"NSH 3601", "title"=>"Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/ken010.jpg", "level"=>"faculty", "first_name"=>"Ken"},
{"last_name"=>"Kraut", "room"=>"NSH 3515", "title"=>"Herbert A. Simon Professor of Human-Computer Interaction", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/bob-1-2006-crop4_0.jpg", "level"=>"faculty", "first_name"=>"Robert"},
{"last_name"=>"Lindqvist", "room"=>"NSH 2602 West", "title"=>"Post Doctoral Fellow", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/HCIIface2.jpg", "level"=>"faculty", "first_name"=>"Janne"},
{"last_name"=>"Mankoff", "room"=>"Jen&#039;s Office: NSH 2405A", "title"=>"Associate Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Mankoff_March09.jpg", "level"=>"faculty", "first_name"=>"Jennifer"},
{"last_name"=>"Matsuda", "room"=>"NSH 2619", "title"=>"Systems Scientist", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/20090314_HCII.jpg", "level"=>"faculty", "first_name"=>"Noboru"},
{"last_name"=>"McLaren", "room"=>"NSH 2602 I", "title"=>"Senior Systems Scientist", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/20090413-DSC_0196.jpg", "level"=>"faculty", "first_name"=>"Bruce"},
{"last_name"=>"Morris", "room"=>"GHC 4117", "title"=>"Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/morris-03-2009.jpg", "level"=>"faculty", "first_name"=>"James"},
{"last_name"=>"Myers", "room"=>"NSH 3517", "title"=>"Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Myers_March09.jpg", "level"=>"faculty", "first_name"=>"Brad"},
{"last_name"=>"Neuwirth", "room"=>"BH 145F", "title"=>"Professor, English", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/neuwirth.web.2009.jpg", "level"=>"faculty", "first_name"=>"Christine"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Ogan+2011+photo.jpg.jpg", "title"=>"Postdoc", "last_name"=>"Ogan", "level"=>"faculty", "first_name"=>"Amy"},
{"last_name"=>"Paulos", "room"=>"NSH 3612E", "title"=>"Assistant Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Paulos_March09.jpg", "level"=>"faculty", "first_name"=>"Eric"},
{"last_name"=>"Ros√©", "room"=>"NSH 4531", "title"=>"Assistant Professor, HCII and Language Technologies Institute", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Rose_March09.jpg", "level"=>"faculty", "first_name"=>"Carolyn"},
{"last_name"=>"Scheines", "room"=>"BH 135", "title"=>"Professor, Head of Philosophy Dept.", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/scheines_0.jpg", "level"=>"faculty", "first_name"=>"Richard"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/DanS_March09.jpg", "title"=>"Buhl University Professor of Computer Science and Electrical and Computer Engineering", "last_name"=>"Siewiorek", "level"=>"faculty", "first_name"=>"Daniel"},
{"last_name"=>"Stamper", "room"=>"NSH 2602L", "title"=>"Systems Scientist", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/john.jpg", "level"=>"faculty", "first_name"=>"John"},
{"level"=>"faculty", "title"=>"Post Doctoral Fellow", "last_name"=>"Stuart", "room"=>"NSH 2614", "first_name"=>"H."},
{"last_name"=>"Tunc-Pekkan", "room"=>"NSH 2602B", "title"=>"Post Doctoral Fellow", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/_MG_3055.jpg", "level"=>"faculty", "first_name"=>"Zelha"},
{"last_name"=>"Waibel", "room"=>"NSH 2602C", "title"=>"Professor, Language Technologies Institute", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/waibel_small-2.jpg", "level"=>"faculty", "first_name"=>"Alexander"},
{"last_name"=>"Yudelson", "room"=>"NSH 2602K", "title"=>"Post Doctoral Fellow", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/HCII_Yudelson_130.jpg", "level"=>"faculty", "first_name"=>"Michael"},
{"last_name"=>"Zimmerman", "room"=>"NSH 2504F", "title"=>"Associate Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/faculty/Zimmerman_March09.jpg", "level"=>"faculty", "first_name"=>"John"},
{"last_name"=>"Baskinger", "room"=>"MM207D", "title"=>"Associate Professor of Industrial Design", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/hcii_square.jpg", "level"=>"faculty", "first_name"=>"Mark"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/LenBass.jpg", "title"=>"Senior Member of Technical Staff", "last_name"=>"Bass", "level"=>"faculty", "first_name"=>"Len"},
{"level"=>"faculty", "title"=>"Faculty, Entertainment Technology Center", "last_name"=>"Blaine", "first_name"=>"Tina"},
{"last_name"=>"Boyarski", "room"=>"MM 110", "title"=>"Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/Boyarski.web.2009.jpg", "level"=>"faculty", "first_name"=>"Daniel"},
{"last_name"=>"Brusilovsky", "room"=>"704 IS Building, 135 N. Bellefield", "title"=>"Associate Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/brusilovsky-llbean.jpg", "level"=>"faculty", "first_name"=>"Peter"},
{"last_name"=>"Christel", "room"=>"PTC 3101", "title"=>"Research Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/Mike_2008.png", "level"=>"faculty", "first_name"=>"Mike"},
{"last_name"=>"Cranor", "room"=>"CIC 2207", "title"=>"Associate Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/lorrie-headshot.jpg", "level"=>"faculty", "first_name"=>"Lorrie"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/Dannenberg_small.jpg", "title"=>"Senior Research Computer Scientist, School of Computer Science", "last_name"=>"Dannenberg", "level"=>"faculty", "first_name"=>"Roger"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/MEskenazi.jpg", "title"=>"Systems Scientist, Language Technologies Institute", "last_name"=>"Eskenazi", "level"=>"faculty", "first_name"=>"Maxine"},
{"last_name"=>"Fahlman", "room"=>"Wean 8214", "title"=>"Research Professor", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/SEF2007-small.jpg", "level"=>"faculty", "first_name"=>"Scott"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/c-gonzalez.jpg", "title"=>"Associate Research Professor and Director, DDMLab, Social and Decision Sciences Department", "last_name"=>"Gonzalez", "level"=>"faculty", "first_name"=>"Cleotilde"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/gross_small.jpg", "title"=>"Professor, Computational Design, School of Architecture", "last_name"=>"Gross", "level"=>"faculty", "first_name"=>"Mark"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/herbsleb.jpg", "title"=>"Professor, School of Computer Science, Director, Software Industry Center", "last_name"=>"Herbsleb", "level"=>"faculty", "first_name"=>"James"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/Hodgins_Jessica.jpg", "title"=>"Professor, Robotics Institute", "last_name"=>"Hodgins", "level"=>"faculty", "first_name"=>"Jessica"},
{"level"=>"faculty", "title"=>"Assistant Professor, Psychology Dept.", "last_name"=>"Holt", "first_name"=>"Lori"},
{"last_name"=>"Jones", "room"=>"BH367", "title"=>"Teaching Professor of French and Computer-Assisted Language Learning", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/jones.jpg", "level"=>"faculty", "first_name"=>"Christopher"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/TKanade.jpg", "title"=>"Professor, Robotics Institute, Computer Science Department", "last_name"=>"Kanade", "level"=>"faculty", "first_name"=>"Takeo"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/DavidKaufer.jpg", "title"=>"Head, English Dept.", "last_name"=>"Kaufer", "level"=>"faculty", "first_name"=>"David"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/SamLeinhardt.jpg", "title"=>"President and CEO, Penthera Technologies, Inc.", "last_name"=>"Leinhardt", "level"=>"faculty", "first_name"=>"Samuel"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/PLucas.jpg", "title"=>"CEO, MAYA Design Group, Inc.", "last_name"=>"Lucas", "level"=>"faculty", "first_name"=>"Peter"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/DMarinelli.jpg", "title"=>"Co-Director, Entertainment Technology Center", "last_name"=>"Marinelli", "level"=>"faculty", "first_name"=>"Don"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/RMartin.jpg", "title"=>"Adjunct Principal Systems Scientist, Robotics Institute", "last_name"=>"Martin", "level"=>"faculty", "first_name"=>"Richard"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/RMaxion.jpg", "title"=>"Principal Systems Scientist, Computer Science Dept.", "last_name"=>"Maxion", "level"=>"faculty", "first_name"=>"Roy"},
{"level"=>"faculty", "title"=>"Visiting Assistant Professor", "last_name"=>"Miller", "first_name"=>"Jill"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/TomMitchell.jpg", "title"=>"Fredkin Professor of AI and Learning, Director, Center for Automated Learning and Discovery (CALD)", "last_name"=>"Mitchell", "level"=>"faculty", "first_name"=>"Tom"},
{"last_name"=>"Mostow", "room"=>"NSH 4103", "title"=>"Research Professor, Robotics Institute, Language Technologies Institute, HCII, Center for Automated Learning and Discovery, PIER", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/Mostow_J.jpg", "level"=>"faculty", "first_name"=>"Jack"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/RajReddy.jpg", "title"=>"Simon University Professor, School of Computer Science", "last_name"=>"Reddy", "level"=>"faculty", "first_name"=>"Raj"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/LReder.jpg", "title"=>"Professor, Psychology", "last_name"=>"Reder", "level"=>"faculty", "first_name"=>"Lynne"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/RRosenfeld.jpg", "title"=>"Professor, LTI, CALD, CSD", "last_name"=>"Rosenfeld", "level"=>"faculty", "first_name"=>"Roni"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/ARudnicky.jpg", "title"=>"Senior Systems Scientist, Computer Science Dept.", "last_name"=>"Rudnicky", "level"=>"faculty", "first_name"=>"Alexander"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/rummel.jpg", "title"=>"Professor, Educational Psychology, Ruhr-Universitat Bochum, Germany", "last_name"=>"Rummel", "level"=>"faculty", "first_name"=>"Nikol"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/Norman+Sadeh_Locaccino_Web_low_res.jpg", "title"=>"Professor, School of Computer Science", "last_name"=>"Sadeh", "level"=>"faculty", "first_name"=>"Norman"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/Jesse_Schell.jpg", "title"=>"Assistant Professor of the Practice, Entertainment Technology Center", "last_name"=>"Schell", "level"=>"faculty", "first_name"=>"Jesse"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/BillScherlis.jpg", "title"=>"Principal Research Scientist, Director, Information Technology Center", "last_name"=>"Scherlis", "level"=>"faculty", "first_name"=>"William"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/MaryShaw.jpg", "title"=>"J. Perlis Professor, Computer Science Dept.", "last_name"=>"Shaw", "level"=>"faculty", "first_name"=>"Mary"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/MelSiegel.jpg", "title"=>"Associate Research Professor, Robotics Institute", "last_name"=>"Siegel", "level"=>"faculty", "first_name"=>"Mel"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/ScottStevens.jpg", "title"=>"Senior Systems Scientist, ETC, HCII", "last_name"=>"Stevens", "level"=>"faculty", "first_name"=>"Scott"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/straus_susan.18.150.jpg", "title"=>"Adjunct Associate Professor, Behavioral Scientist, RAND", "last_name"=>"Straus", "level"=>"faculty", "first_name"=>"Susan"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/KatiaSycara.jpg", "title"=>"Principal Research Scientist, Robotics Institute", "last_name"=>"Sycara", "level"=>"faculty", "first_name"=>"Katia"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/affil_faculty/AlonsoVera.jpg", "title"=>"Adjunct Associate Research Scientist, Carnegie Mellon West", "last_name"=>"Vera", "level"=>"faculty", "first_name"=>"Alonso"},
{"level"=>"faculty", "last_name"=>"von Ahn", "first_name"=>"Luis"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/20090319_DSC_1003+more+awake.png", "level"=>"phd", "last_name"=>"Aleahmad", "room"=>"NSH 3603", "first_name"=>"Turadg"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/20090220_DSC_0136.jpg", "level"=>"phd", "last_name"=>"Balakrishnan", "first_name"=>"Aruna"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/20090220_DSC_0144.jpg", "level"=>"phd", "last_name"=>"Burke", "room"=>"300 S. Craig St., Room 206", "first_name"=>"Moira"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/cropped+Chang+F10+F10+Kerrys+first+choice+for+web+DSC_4592.jpg", "level"=>"phd", "last_name"=>"Chang", "room"=>"NSH 4611", "first_name"=>"Kerry"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/tawanna.jpg", "level"=>"phd", "last_name"=>"Dillahunt", "room"=>"NSH 4619", "first_name"=>"Tawanna"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/chloe.jpg", "level"=>"phd", "last_name"=>"Fan", "room"=>"NSH 4606", "first_name"=>"Chloe"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/cropped+Gulotta+F10+photo+DSC_4650.jpg", "level"=>"phd", "last_name"=>"Gulotta", "room"=>"NSH 4609", "first_name"=>"Rebecca"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/20090305_DSC_0571.jpg", "level"=>"phd", "last_name"=>"Gweon", "first_name"=>"Gahgene"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/20090319_DSC_0993.jpg", "level"=>"phd", "last_name"=>"Harrison", "room"=>"NSH 3612", "first_name"=>"Chris"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/eiji3.jpg", "level"=>"phd", "last_name"=>"Hayashi", "first_name"=>"Eiji"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/20090306_DSC_0681.jpg", "level"=>"phd", "last_name"=>"Howley", "first_name"=>"Iris"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/kevin.jpg", "level"=>"phd", "last_name"=>"Huang", "first_name"=>"Kevin"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/Kang+F10+cropped+photo+DSC_5421.jpg", "level"=>"phd", "last_name"=>"Kang", "room"=>"NSH 4617", "first_name"=>"Ruogu"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/20090319_DSC_1042.jpg", "level"=>"phd", "last_name"=>"Kim", "room"=>"NSH 2502", "first_name"=>"Sunyoung"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/Kinnaird+F10+DSC_4752_0.jpg", "level"=>"phd", "last_name"=>"Kinnaird", "room"=>"NSH 4617", "first_name"=>"Peter"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/anuj.jpg", "level"=>"phd", "last_name"=>"Kumar", "room"=>"NSH 3611", "first_name"=>"Anuj"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/staceyk.jpg", "level"=>"phd", "last_name"=>"Kuznetsov", "first_name"=>"Stacey"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/mattlee.jpg", "level"=>"phd", "last_name"=>"Lee", "room"=>"NSH 4607", "first_name"=>"Matthew"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/HCII_MinKyungLee.jpg", "level"=>"phd", "last_name"=>"Lee", "first_name"=>"Min"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/cropped+Li+Ian+preF06.jpg", "level"=>"phd", "last_name"=>"Li", "first_name"=>"Ian"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/brianlim.jpg", "level"=>"phd", "last_name"=>"Lim", "room"=>"NSH 4619", "first_name"=>"Brian"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/website-20090820_124617.jpg", "level"=>"phd", "last_name"=>"Lomas", "room"=>"NSH 4611", "first_name"=>"James"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/cropped+Yanjin+Long+F10+photo+DSC_4605.jpg", "level"=>"phd", "last_name"=>"Long", "room"=>"NSH 4611", "first_name"=>"Yanjin"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/Gabi+Marcu+photo+July+2009.PNG", "level"=>"phd", "last_name"=>"Marcu", "room"=>"NSH 4617", "first_name"=>"Gabriela"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/HCI_headshot.jpg", "level"=>"phd", "last_name"=>"Marlow", "first_name"=>"Jennifer"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/will.jpg", "level"=>"phd", "last_name"=>"Odom", "room"=>"NSH 3611", "first_name"=>"Will"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/20090220_DSC_0034.jpg", "level"=>"phd", "last_name"=>"Oney", "first_name"=>"Stephen"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/cropped+James+Pierce.jpg", "level"=>"phd", "last_name"=>"Pierce", "first_name"=>"James"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/martina.jpg", "level"=>"phd", "last_name"=>"Rau", "first_name"=>"Martina"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/croppedRzeszotarski+F10+DSC_4658.jpg", "level"=>"phd", "last_name"=>"Rzeszotarski", "room"=>"NSH 4609", "first_name"=>"Jeffrey"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/julia.jpg", "level"=>"phd", "last_name"=>"Schwarz", "first_name"=>"Julia"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/cropped+Stampfer+F10+photo+DSC_4631.jpg", "level"=>"phd", "last_name"=>"Stampfer", "room"=>"NSH 4609", "first_name"=>"Eliane"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/jason-300kb-square.jpg", "level"=>"phd", "last_name"=>"Wiese", "room"=>"Newell Simon Hall 3603", "first_name"=>"Jason"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/20090319_DSC_0926.jpg", "level"=>"phd", "last_name"=>"Wylie", "first_name"=>"Ruth"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/phd/HaiyiZhu3.jpg", "level"=>"phd", "last_name"=>"Zhu", "room"=>"NSH 4606", "first_name"=>"Haiyi"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-26.jpg", "level"=>"masters", "last_name"=>"Andrianoff", "first_name"=>"Timothy"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-78.jpg", "level"=>"masters", "last_name"=>"Auw", "first_name"=>"Christie"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-06.jpg", "level"=>"masters", "last_name"=>"Awori", "first_name"=>"Kagonya"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-20.jpg", "level"=>"masters", "last_name"=>"Bai", "first_name"=>"Julie"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-145.jpg", "level"=>"masters", "last_name"=>"Bariola", "first_name"=>"Pablo"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-44.jpg", "level"=>"masters", "last_name"=>"Caravelli", "first_name"=>"Paul"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-153.jpg", "level"=>"masters", "last_name"=>"Chandra", "first_name"=>"Hitee"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-117.jpg", "level"=>"masters", "last_name"=>"Chatterji", "first_name"=>"Vikram"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-110.jpg", "level"=>"masters", "last_name"=>"Chi", "first_name"=>"Chung-Yi"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-51.jpg", "level"=>"masters", "last_name"=>"Chua", "first_name"=>"Chong"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-15.jpg", "level"=>"masters", "last_name"=>"Clark", "first_name"=>"Emily"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-138.jpg", "level"=>"masters", "last_name"=>"Coelho", "first_name"=>"Paulo"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-136.jpg", "level"=>"masters", "last_name"=>"Dudiak", "first_name"=>"Eric"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-88.jpg", "level"=>"masters", "last_name"=>"Effner", "first_name"=>"Troy"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-38.jpg", "level"=>"masters", "last_name"=>"Fang", "first_name"=>"Zhenshuo"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-05.jpg", "level"=>"masters", "last_name"=>"Fernandez", "first_name"=>"Nicole"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-132.jpg", "level"=>"masters", "last_name"=>"Flowers", "first_name"=>"John"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-22.jpg", "level"=>"masters", "last_name"=>"Freitas", "first_name"=>"Daniel"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-114.jpg", "level"=>"masters", "last_name"=>"Ganesan", "first_name"=>"Arun"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/AndrewGillespie_photo.jpg", "level"=>"masters", "last_name"=>"Gillespie", "first_name"=>"Drew"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-28.jpg", "level"=>"masters", "last_name"=>"Giraldo", "first_name"=>"Mauricio"},
{"level"=>"masters", "last_name"=>"Gon√ßalves", "first_name"=>"Andreia"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-64.jpg", "level"=>"masters", "last_name"=>"Gotow", "first_name"=>"J."},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-48.jpg", "level"=>"masters", "last_name"=>"Gupta", "first_name"=>"Bhavana"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-47.jpg", "level"=>"masters", "last_name"=>"Gupta", "first_name"=>"Sanchit"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-33.jpg", "level"=>"masters", "last_name"=>"Holtzblatt", "first_name"=>"Shoshana"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-107.jpg", "level"=>"masters", "last_name"=>"Horstman", "first_name"=>"John"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/Jain.jpg", "level"=>"masters", "last_name"=>"Jain", "first_name"=>"Anubhuti"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/brendan+kiu.jpg", "level"=>"masters", "last_name"=>"Kiu", "first_name"=>"Brendan"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-12.jpg", "level"=>"masters", "last_name"=>"Kurani", "first_name"=>"Nisha"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-17.jpg", "level"=>"masters", "last_name"=>"Lee", "first_name"=>"Jooyong"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-128.jpg", "level"=>"masters", "last_name"=>"Lin", "first_name"=>"Clifton"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-36.jpg", "level"=>"masters", "last_name"=>"Lin", "first_name"=>"Honray"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/square_IMG_7332-1-1.jpg", "level"=>"masters", "last_name"=>"Lin", "first_name"=>"Susan"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-127.jpg", "level"=>"masters", "last_name"=>"Luong", "first_name"=>"Raymond"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-144.jpg", "level"=>"masters", "last_name"=>"Ma", "first_name"=>"Cong"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-151.jpg", "level"=>"masters", "last_name"=>"Martins", "first_name"=>"Maria"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-97.jpg", "level"=>"masters", "last_name"=>"Micklin", "first_name"=>"Claire"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-73.jpg", "level"=>"masters", "last_name"=>"Mulholland", "first_name"=>"James"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-43.jpg", "level"=>"masters", "last_name"=>"Nagda", "first_name"=>"Mehwish"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-13.jpg", "level"=>"masters", "last_name"=>"Ng", "first_name"=>"Tiffany"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/mollynix.jpg", "level"=>"masters", "last_name"=>"Nix", "first_name"=>"Molly"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-74.jpg", "level"=>"masters", "last_name"=>"Paepcke", "first_name"=>"Stephanie"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-98.jpg", "level"=>"masters", "last_name"=>"Pan", "first_name"=>"Alan"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-02.jpg", "level"=>"masters", "last_name"=>"Park", "first_name"=>"Angela"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-29.jpg", "level"=>"masters", "last_name"=>"Penney", "first_name"=>"Ward"},
{"level"=>"masters", "last_name"=>"Poor", "first_name"=>"Tony"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-56.jpg", "level"=>"masters", "last_name"=>"Pryor", "first_name"=>"Jared"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/preethi_raju_pic.png", "level"=>"masters", "last_name"=>"Raju", "first_name"=>"Preethi"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-133.jpg", "level"=>"masters", "last_name"=>"Ramasubramanian", "first_name"=>"Sriram"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-141.jpg", "level"=>"masters", "last_name"=>"Randall", "first_name"=>"David"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-70.jpg", "level"=>"masters", "last_name"=>"Rivard", "first_name"=>"Kathryn"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-54.jpg", "level"=>"masters", "last_name"=>"Savage", "first_name"=>"Trevor"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-87.jpg", "level"=>"masters", "last_name"=>"Schwartzman", "first_name"=>"Emily"},
{"level"=>"masters", "last_name"=>"Shon", "first_name"=>"Eva"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-108.jpg", "level"=>"masters", "last_name"=>"Shuster", "first_name"=>"Mark"},
{"level"=>"masters", "last_name"=>"Sugarman", "first_name"=>"Spencer"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-25.jpg", "level"=>"masters", "last_name"=>"Tan", "first_name"=>"Nastasha"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-82.jpg", "level"=>"masters", "last_name"=>"Vandy", "first_name"=>"Sypraseuth"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-40.jpg", "level"=>"masters", "last_name"=>"Verma", "first_name"=>"Namrata"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-08.jpg", "level"=>"masters", "last_name"=>"Wang", "first_name"=>"Yuan"},
{"image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/mhci/NPFN-124.jpg", "level"=>"masters", "last_name"=>"Yang", "first_name"=>"Ya-Chun"},
{"level"=>"masters", "last_name"=>"Zhang", "first_name"=>"Anthony"},
{"level"=>"staff", "title"=>"Administrative Associate", "last_name"=>"Homyak", "room"=>"3501B", "first_name"=>"Alex"},
{"last_name"=>"Bodnar", "room"=>"NSH 3526", "title"=>"Administrative Associate", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/web.photo.2009_0.jpg", "level"=>"staff", "first_name"=>"Jo"},
{"last_name"=>"Carrozza", "room"=>"NSH 3507", "title"=>"Assistant Business Manager", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/mlc_0.jpg", "level"=>"staff", "first_name"=>"Melissa"},
{"last_name"=>"Casillas", "room"=>"NSH 3526", "title"=>"Administrative Associate", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/David+Casillas-1.jpg", "level"=>"staff", "first_name"=>"David"},
{"last_name"=>"D&#039;Amico", "room"=>"NSH 4527", "title"=>"Project Manager", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/web.photo.2009.jpg", "level"=>"staff", "first_name"=>"Marian"},
{"last_name"=>"Gittleman", "room"=>"NSH 3521", "title"=>"Manager, Director&#039;s Office", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/Michele+small+picture.jpg", "level"=>"staff", "first_name"=>"Michele"},
{"level"=>"staff", "title"=>"Administrative Coordinator", "last_name"=>"King", "room"=>"NSH 3526", "first_name"=>"Rebecca"},
{"last_name"=>"Kravitz", "room"=>"NSH 4615", "title"=>"Graduate Program Coordinator", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/Queenie+F10+photo+DSC_4583.jpg", "level"=>"staff", "first_name"=>"Queenie"},
{"level"=>"staff", "title"=>"Business Manager", "last_name"=>"Murrin-Macey", "room"=>"NSH 3511", "first_name"=>"Denise"},
{"last_name"=>"Scott", "room"=>"NSH 3509", "title"=>"Office Staff III", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/web.photo.2009_1.jpg", "level"=>"staff", "first_name"=>"Mary"},
{"last_name"=>"Stanley", "room"=>"300 SCRG Rm. 208", "title"=>"Program Assistant", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/J.+Stanley+Headshot_small.jpg", "level"=>"staff", "first_name"=>"Jessica"},
{"last_name"=>"Szegedy", "room"=>"NSH 3526", "title"=>"Administrative Coordinator and HCII Undergraduate Program Coordinator", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/photo_0.JPG", "level"=>"staff", "first_name"=>"Indra"},
{"last_name"=>"Vento", "room"=>"NSH 3509", "title"=>"Research Administrator", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/OB2N9191_1.jpg", "level"=>"staff", "first_name"=>"Lisa"},
{"last_name"=>"Willis", "room"=>"300 SCRG Rm. 229", "title"=>"Academic Program Coordinator", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/ME.jpg", "level"=>"staff", "first_name"=>"Nicole"},
{"level"=>"staff", "title"=>"Managing Director, PSLC", "last_name"=>"Bett", "room"=>"NSH 2602I", "first_name"=>"Michael"},
{"level"=>"staff", "title"=>"Research Assistant", "last_name"=>"Brooks", "first_name"=>"Maria"},
{"last_name"=>"Carvalho", "room"=>"NSH 2602H", "title"=>"Research Associate", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/adriana.jpg", "level"=>"staff", "first_name"=>"Adriana"},
{"last_name"=>"Chang", "room"=>"NSH 2620C", "title"=>"Senior Research Programmer", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/Chang.jpg", "level"=>"staff", "first_name"=>"Chang-Hsin"},
{"level"=>"staff", "title"=>"Research Programmer", "last_name"=>"Cheng", "room"=>"NSH 2620A", "first_name"=>"Hui"},
{"level"=>"staff", "title"=>"Senior Research Programmer", "last_name"=>"Cosgrove", "room"=>"GHC 4007", "first_name"=>"Dennis"},
{"level"=>"staff", "title"=>"Senior Research Programmer", "last_name"=>"Culyba", "room"=>"GHC 4007", "first_name"=>"David"},
{"last_name"=>"Demi", "room"=>"NSH 2602J", "title"=>"Senior Research Programmer", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/sdemi.jpg", "level"=>"staff", "first_name"=>"Sandra"},
{"level"=>"staff", "title"=>"Research Assistant", "last_name"=>"Emerson", "room"=>"NSH 2602", "first_name"=>"Eric"},
{"last_name"=>"Faulring", "room"=>"417 SCRG 302B", "title"=>"Research Programmer", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/Andrew+Faulring_0.jpg", "level"=>"staff", "first_name"=>"Andrew"},
{"level"=>"staff", "title"=>"Research Programmer", "last_name"=>"Keiser", "room"=>"NSH 2602A", "first_name"=>"Victoria"},
{"last_name"=>"Kusbit", "room"=>"NSH 2619", "title"=>"PSLC Research Manager", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/gkusbit.jpg", "level"=>"staff", "first_name"=>"Gail"},
{"last_name"=>"Leber", "room"=>"NSH 2602J", "title"=>"Documentation Specialist", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/portrait-20090319_DSC_0919-250px.png", "level"=>"staff", "first_name"=>"Brett"},
{"level"=>"staff", "title"=>"Research Assistant", "last_name"=>"Luo", "first_name"=>"Rosemary"},
{"last_name"=>"MacLaren", "room"=>"NSH 2620B", "title"=>"Senior Research Programmer", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/BenMacLaren.jpg", "level"=>"staff", "first_name"=>"Ben"},
{"level"=>"staff", "title"=>"Research Associate", "last_name"=>"McLaughlin", "room"=>"NSH 2620A", "first_name"=>"Elizabeth"},
{"last_name"=>"Morrison", "room"=>"300 SCRG 203", "title"=>"Senior Research Programmer", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/morrison.jpg", "level"=>"staff", "first_name"=>"Don"},
{"level"=>"staff", "title"=>"Systems/Software Associate", "last_name"=>"Ojeda", "room"=>"NSH 2504B", "first_name"=>"Marcos"},
{"level"=>"staff", "title"=>"Research Programmer", "last_name"=>"Popescu", "room"=>"NSH 2612", "first_name"=>"Octav"},
{"level"=>"staff", "title"=>"Research Programmer", "last_name"=>"Raizada", "room"=>"NSH 2602A", "first_name"=>"Rohan"},
{"level"=>"staff", "title"=>"Research Programmer", "last_name"=>"Rojas", "room"=>"NSH 2502", "first_name"=>"Julian"},
{"level"=>"staff", "title"=>"Research Programmer", "last_name"=>"Ringenberg", "room"=>"NSH 2602B", "first_name"=>"Michael"},
{"level"=>"staff", "title"=>"Research Assistant", "last_name"=>"Schreiber", "room"=>"NSH 2602B", "first_name"=>"Abraham"},
{"last_name"=>"Sewall", "room"=>"NSH 2617", "title"=>"Project Director", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/Sewall_small.jpg", "level"=>"staff", "first_name"=>"Jonathan"},
{"last_name"=>"Skogsholm", "room"=>"NSH 2602J", "title"=>"PSLC DataShop Manager", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/HCII+Photos+%28No+MHCI%29_Page_048.jpg", "level"=>"staff", "first_name"=>"Alida"},
{"level"=>"staff", "title"=>"Software Engineer", "last_name"=>"Springfield", "room"=>"NSH 2504, EDSH 234", "first_name"=>"James"},
{"level"=>"staff", "title"=>"Research Assistant", "last_name"=>"Tassini", "room"=>"NSH 2502B", "first_name"=>"Kevin"},
{"level"=>"staff", "title"=>"Research Programmer", "last_name"=>"Thompson", "room"=>"NSH 2504", "first_name"=>"Robert"},
{"last_name"=>"Velsen", "room"=>"NSH 2619", "title"=>"Research Programmer", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/Van_Velsen_Martin.JPG", "level"=>"staff", "first_name"=>"Martin"},
{"last_name"=>"Wagner", "room"=>"NSH 2620B", "title"=>"Research Associate II", "image"=>"http://www.hcii.cmu.edu/system/files/imagecache/Image_resize/images/admin_staff/Wagner.jpg", "level"=>"staff", "first_name"=>"Angela"},
{"level"=>"staff", "title"=>"Research Associate", "last_name"=>"Watson", "room"=>"NSH 2602G", "first_name"=>"Shayna"},
{"level"=>"staff", "title"=>"Research Associate", "last_name"=>"Yarzebinski", "room"=>"NSH 2602", "first_name"=>"Evelyn"},
{"level"=>"staff", "title"=>"Systems Support Specialist", "last_name"=>"Yu", "room"=>"GHC 4007", "first_name"=>"Gabriel"},
{"level"=>"staff", "title"=>"Sr. Research Programmer", "last_name"=>"Yu", "room"=>"NSH 2602G", "first_name"=>"Shanwen"}]
)